### PR TITLE
Update open_iconic_flutter

### PR DESCRIPTION
**Pull request by ghost**
This is needed to support the latest dart sdk version. Its already been done upstream.
https://github.com/brianegan/chewie/blob/master/pubspec.yaml

### CODE REVIEW

**Comment by ghost** [comment]
It would be greate if this could be merged fast. Want it try it out immediately.

**Comment by ghost** [comment]
Please Marge. Please.
tumblr_oof09ke3qz1qh59n0o7_400

**Comment by ghost** [comment]
please-marge-let-me-have-that-meat

**Comment by ghost** [comment]
@bostrot You still there?

**Comment by bostrot** [comment]
@pyros2097 Thanks for this pr 😄

**Pull request merged**
